### ISSUE TITLE
Could you an option to disable mail system?

### ISSUE THREAD

**Issue by 5igm** [trentech/SimpleChat#4]
I am using nucleus which owns a mail system. Both of simple chat and nucleus use "/mail" as command. Could you add a option to disable mail system in simple chat?

**Comment by trentech** [comment]
Sponge has a solution for problems like this

https://forums.spongepowered.org/t/conflicting-plugin-commands-look-no-further/11011

**Comment by 5igm** [comment]
Thank you very much!
